[date]
enable = false
interval = "1m"
format = "Jan _2 2006 (Mon) 3:04 PM"
icons = [ "󱑊", "󱐿", "󱑀", "󱑁", "󱑂", "󱑃", "󱑄", "󱑅", "󱑆", "󱑇", "󱑈", "󱑉" ]

[ram]
enable = false
interval = "1s"
icons = [ " ", "▁", "▂", "▃", "▄", "▅", "▆", "▇", "█" ]

[swap]
enable = false
interval = "1s"
icons = [ " ", "▁", "▂", "▃", "▄", "▅", "▆", "▇", "█" ]

[cpu]
enable = false
interval = "1s"
icons = [ " ", "▁", "▂", "▃", "▄", "▅", "▆", "▇", "█" ]

[bri]
enable = false
icons = [ "󰃞", "󰃟", "󰃝", "󰃠" ]

[bat]
enable = false
interval = "1m"
icons = [ "", "", "", "", "" ]

[music]
enable = false
scrollInterval = "1s"
format = "%AlbumArtist% - %Title%"
limit = 20

[vol]
enable = false
discardInterval = "10ms"
icons = [ "󰕿", "󰖀", "󰕾" ]

[uptime]
enable = false
interval = "1m"

[user]
enable = false

[disk]
enable = false
interval = "1m"
disks = [ "/" ]
icons = [ " ", "▁", "▂", "▃", "▄", "▅", "▆", "▇", "█" ]

[hyprland]
enable = false
scrollInterval = "1s"
limit = 20

[net]
enable = true
interval = "1m"
scrollInterval = "1s"
limit = 20
offIcon = "󰤭"
ethIcon = "󰈀"
wifiIcons = [ "󰤯", "󰤟", "󰤢", "󰤥", "󰤨" ]
