[bat]
enable = false
icons = ["󰂎", "󰁺", "󰁻", "󰁼", "󰁽", "󰁾", "󰁿", "󰂀", "󰂁", "󰂂", "󰁹"]
interval = "1m"

[bluetooth]
enable = true
icons = ["󰂎", "󰁺", "󰁻", "󰁼", "󰁽", "󰁾", "󰁿", "󰂀", "󰂁", "󰂂", "󰁹"]
limit = 20
scrollInterval = "1s"

[bri]
enable = false
icons = ["󰃞", "󰃟", "󰃝", "󰃠"]

[cpu]
enable = false
icons = [" ", "▁", "▂", "▃", "▄", "▅", "▆", "▇", "█"]
interval = "1s"

[date]
enable = false
format = "Jan _2 2006 (Mon) 3:04 PM"
icons = ["󱑊", "󱐿", "󱑀", "󱑁", "󱑂", "󱑃", "󱑄", "󱑅", "󱑆", "󱑇", "󱑈", "󱑉"]
interval = "1m"

[disk]
disks = ["/"]
enable = false
icons = [" ", "▁", "▂", "▃", "▄", "▅", "▆", "▇", "█"]
interval = "1m"

[hyprland]
enable = false
limit = 20
scrollInterval = "1s"

[music]
enable = false
format = "%AlbumArtist% - %Track% - %Album% - %Title%"
limit = 20
scrollInterval = "1s"

[net]
enable = false
ethIcon = "󰈀"
interval = "1m"
limit = 20
offIcon = "󰤭"
scrollInterval = "1s"
wifiIcons = ["󰤯", "󰤟", "󰤢", "󰤥", "󰤨"]

[ram]
enable = false
icons = [" ", "▁", "▂", "▃", "▄", "▅", "▆", "▇", "█"]
interval = "1s"

[swap]
enable = false
icons = [" ", "▁", "▂", "▃", "▄", "▅", "▆", "▇", "█"]
interval = "1s"

[uptime]
enable = false
interval = "1m"

[user]
enable = false

[vol]
discardInterval = "10ms"
enable = false
icons = ["󰕿", "󰖀", "󰕾"]
